# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/huawei/bln/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/huawei/bln

PRODUCT_COPY_FILES += \
    vendor/huawei/bln/proprietary/odm/etc/audio/algorithm/algorithm_BERLIN_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/algorithm/algorithm_BERLIN_normal.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/algorithm/algorithm_hi6250_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/algorithm/algorithm_hi6250_normal.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/dts/dts_BERLIN_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/dts/dts_BERLIN_normal.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/dts/dts_default.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/dts/dts_default.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/dts/dts_hi6250_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/dts/dts_hi6250_normal.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/hissc/mixer_paths_BERLIN.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/mixer_paths_BERLIN.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/hissc/mixer_paths_hi6250.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/mixer_paths_hi6250.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/hissc/mixer_volumes_BERLIN_ce.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/mixer_volumes_BERLIN_ce.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/hissc/mixer_volumes_BERLIN_cmcciot.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/mixer_volumes_BERLIN_cmcciot.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/hissc/mixer_volumes_BERLIN_gcf.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/mixer_volumes_BERLIN_gcf.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/hissc/mixer_volumes_BERLIN_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/mixer_volumes_BERLIN_normal.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/hissc/mixer_volumes_BERLIN_unicomiot.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/mixer_volumes_BERLIN_unicomiot.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/hissc/mixer_volumes_hi6250_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/mixer_volumes_hi6250_normal.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/hissc/pop_seq_BERLIN.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/pop_seq_BERLIN.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/hissc/pop_seq_hi6250.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/pop_seq_hi6250.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/mbdrc/mbdrc_BERLIN_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/mbdrc/mbdrc_BERLIN_normal.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/mbdrc/mbdrc_default.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/mbdrc/mbdrc_default.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/mbdrc/mbdrc_hi6250_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/mbdrc/mbdrc_hi6250_normal.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/modem/modem_BERLIN_cmcciot.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/modem/modem_BERLIN_cmcciot.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/modem/modem_BERLIN_gcf.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/modem/modem_BERLIN_gcf.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/modem/modem_BERLIN_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/modem/modem_BERLIN_normal.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/modem/modem_BERLIN_unicomiot.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/modem/modem_BERLIN_unicomiot.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/modem/modem_default.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/modem/modem_default.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/modem/modem_hi6250_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/modem/modem_hi6250_normal.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/sws/sws_BERLIN_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/sws/sws_BERLIN_normal.xml \
    vendor/huawei/bln/proprietary/odm/etc/audio/sws/sws_default.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/sws/sws_default.xml \
    vendor/huawei/bln/proprietary/odm/lib64/hwcam/hwcam.hi6250.BERLIN.p.GC2355_LITEON.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.BERLIN.p.GC2355_LITEON.so \
    vendor/huawei/bln/proprietary/odm/lib64/hwcam/hwcam.hi6250.BERLIN.p.HI259_OFILM.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.BERLIN.p.HI259_OFILM.so \
    vendor/huawei/bln/proprietary/odm/lib64/hwcam/hwcam.hi6250.BERLIN.p.HI259_SUNNY.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.BERLIN.p.HI259_SUNNY.so \
    vendor/huawei/bln/proprietary/odm/lib64/hwcam/hwcam.hi6250.BERLIN.p.HI843BLN_OFILM.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.BERLIN.p.HI843BLN_OFILM.so \
    vendor/huawei/bln/proprietary/odm/lib64/hwcam/hwcam.hi6250.BERLIN.p.IMX219BLN_LITEON.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.BERLIN.p.IMX219BLN_LITEON.so \
    vendor/huawei/bln/proprietary/odm/lib64/hwcam/hwcam.hi6250.BERLIN.p.IMX219BLN_SUNNY.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.BERLIN.p.IMX219BLN_SUNNY.so \
    vendor/huawei/bln/proprietary/odm/lib64/hwcam/hwcam.hi6250.BERLIN.p.IMX386_OFILM.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.BERLIN.p.IMX386_OFILM.so \
    vendor/huawei/bln/proprietary/odm/lib64/hwcam/hwcam.hi6250.BERLIN.p.IMX386_SUNNY.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.BERLIN.p.IMX386_SUNNY.so \
    vendor/huawei/bln/proprietary/odm/lib64/hwcam/hwcam.hi6250.BERLIN.p.OV12870_LITEON.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.BERLIN.p.OV12870_LITEON.so \
    vendor/huawei/bln/proprietary/odm/lib64/hwcam/hwcam.hi6250.BERLIN.p.OV12870_OFILM.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.BERLIN.p.OV12870_OFILM.so \
    vendor/huawei/bln/proprietary/odm/lib64/hwcam/hwcam.hi6250.BERLIN.s.GC2355_LITEON.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.BERLIN.s.GC2355_LITEON.so \
    vendor/huawei/bln/proprietary/odm/lib64/hwcam/hwcam.hi6250.BERLIN.s.HI259_OFILM.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.BERLIN.s.HI259_OFILM.so \
    vendor/huawei/bln/proprietary/odm/lib64/hwcam/hwcam.hi6250.BERLIN.s.HI259_SUNNY.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.BERLIN.s.HI259_SUNNY.so \
    vendor/huawei/bln/proprietary/odm/lib64/hwcam/hwcam.hi6250.BERLIN.s.HI843BLN_OFILM.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.BERLIN.s.HI843BLN_OFILM.so \
    vendor/huawei/bln/proprietary/odm/lib64/hwcam/hwcam.hi6250.BERLIN.s.IMX219BLN_LITEON.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.BERLIN.s.IMX219BLN_LITEON.so \
    vendor/huawei/bln/proprietary/odm/lib64/hwcam/hwcam.hi6250.BERLIN.s.IMX219BLN_SUNNY.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.BERLIN.s.IMX219BLN_SUNNY.so \
    vendor/huawei/bln/proprietary/odm/lib64/hwcam/hwcam.hi6250.BERLIN.s.IMX386_OFILM.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.BERLIN.s.IMX386_OFILM.so \
    vendor/huawei/bln/proprietary/odm/lib64/hwcam/hwcam.hi6250.BERLIN.s.IMX386_SUNNY.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.BERLIN.s.IMX386_SUNNY.so \
    vendor/huawei/bln/proprietary/odm/lib64/hwcam/hwcam.hi6250.BERLIN.s.OV12870_LITEON.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.BERLIN.s.OV12870_LITEON.so \
    vendor/huawei/bln/proprietary/odm/lib64/hwcam/hwcam.hi6250.BERLIN.s.OV12870_OFILM.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.BERLIN.s.OV12870_OFILM.so \
    vendor/huawei/bln/proprietary/odm/lib64/hwcam/hwcam.hi6250.m.BERLIN.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.m.BERLIN.so \
    vendor/huawei/bln/proprietary/vendor/lib64/libpn551_fw.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libpn551_fw.so \
    vendor/huawei/bln/proprietary/odm/firmware/ts/berlin_auo_ili9885.bin:$(TARGET_COPY_OUT_ODM)/firmware/ts/berlin_auo_ili9885.bin \
    vendor/huawei/bln/proprietary/odm/firmware/ts/berlin_auo_nt35532.bin:$(TARGET_COPY_OUT_ODM)/firmware/ts/berlin_auo_nt35532.bin \
    vendor/huawei/bln/proprietary/odm/firmware/ts/berlin_boe_nt35532.bin:$(TARGET_COPY_OUT_ODM)/firmware/ts/berlin_boe_nt35532.bin \
    vendor/huawei/bln/proprietary/odm/firmware/ts/berlin_boe_nt35532_lens.bin:$(TARGET_COPY_OUT_ODM)/firmware/ts/berlin_boe_nt35532_lens.bin \
    vendor/huawei/bln/proprietary/odm/firmware/ts/berlin_inx_nt35532.bin:$(TARGET_COPY_OUT_ODM)/firmware/ts/berlin_inx_nt35532.bin \
    vendor/huawei/bln/proprietary/odm/firmware/ts/berlin_inx_nt35532_lens.bin:$(TARGET_COPY_OUT_ODM)/firmware/ts/berlin_inx_nt35532_lens.bin \
    vendor/huawei/bln/proprietary/odm/firmware/ts/berlin_tm_nt35596.bin:$(TARGET_COPY_OUT_ODM)/firmware/ts/berlin_tm_nt35596.bin \
    vendor/huawei/bln/proprietary/odm/firmware/ts/berlin_tm_nt35596_lens.bin:$(TARGET_COPY_OUT_ODM)/firmware/ts/berlin_tm_nt35596_lens.bin \
    vendor/huawei/bln/proprietary/odm/firmware/ts/berlin_tm_otm1901a.bin:$(TARGET_COPY_OUT_ODM)/firmware/ts/berlin_tm_otm1901a.bin \
    vendor/huawei/bln/proprietary/odm/firmware/ts/berlin_tm_r63350.bin:$(TARGET_COPY_OUT_ODM)/firmware/ts/berlin_tm_r63350.bin \
    vendor/huawei/bln/proprietary/odm/firmware/ts/berlin_tm_r63350_lens.bin:$(TARGET_COPY_OUT_ODM)/firmware/ts/berlin_tm_r63350_lens.bin \
    vendor/huawei/bln/proprietary/vendor/etc/libnfc-brcm.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-brcm.conf \
    vendor/huawei/bln/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf
